
runtime: custom
env: flex

network:
  session_affinity: true

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 10

env_variables:
  SPRING_SECURITY_USER_NAME: "admin"
  SPRING_SECURITY_USER_PASSWORD: "SoPra-Group32"
  SPRING_PROFILES_ACTIVE: "production"
  JAVA_TOOL_OPTIONS: "-Xms128m -Xmx400m"
  MAPILLARY_ACCESS_TOKEN: "<MAPILLARY_ACCESS_TOKEN>"