server.port=8080

# Disable H2 console in production
spring.h2.console.enabled=false

# PostgreSQL / Supabase
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.wuarcbmddngqzuzveoka
spring.datasource.password=SoPra-Group32

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false